version: "3"
services:
  myportfolio:
    container_name: myportfolio
    build: .
    restart: always
    env_file:
      - .env
    environment:
      - FLASK_ENV=development
    ports:
      - "5001:5001"
    volumes:
      - .:/portfolio-site
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb:latest
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

volumes:
  mydatabase:
